spring:
     datasource:
             url: jdbc:h2:mem:user
             username: root
             password: root
     jpa:
       show-sql: true
       hibernate:
         ddl-auto: update
     h2:
       console:
         enabled: true